// User actions
export const GET_MOVIE_LIST_START = "GET_MOVIE_LIST_START";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_DETAIL_START = "GET_MOVIE_DETAIL_START";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";



